name: Bug report
description: Create a report to help us improve
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Example Flow
      description: If applicable, add an example of exported json of a flow exhibiting the issue to aid in reproduction.
      render: json
    validations:
      required: false
  - type: input
    attributes:
      label: This package's version (not the Home Assistant add-on verison)
      placeholder: 0.33.1
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Is Node-RED running in Docker?"
      options:
        - "Yes"
        - "No"
        - "Home Assistant add-on"
    validations:
      required: true
  - type: input
    attributes:
      label: Node-RED version
      placeholder: 1.3.5
    validations:
      required: true
  - type: input
    attributes:
      label: Node.js version
      placeholder: 14.17.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem.
    validations:
      required: false
