name: Format Docs (prettier)

on:
  pull_request:
    paths:
      - "docs/**/*.md"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - run: npm install
      - name: Run prettier
        run: npm run docs:lint
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier changes
          branch: ${{ github.head_ref }}
          commit_options: "--no-verify"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
